name: Sync main to gh-pages
on: [workflow_dispatch]
#  push:
 #     branches:
  #      - main
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: branch gh-pages
        run: |
          git status
